"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-qv&bi1etd=g#jse2hnl8*-&n-phvu!3ygze83n15j=3181!(@6')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=["*"])
SITE_URL = env('SITE_URL', default='http://localhost:8000')

# CSRF trusted origins: thêm cả http và https của SITE_URL
_csrf_origins = [SITE_URL]
if SITE_URL.startswith('https://'):
    _csrf_origins.append(SITE_URL.replace('https://', 'http://'))
elif SITE_URL.startswith('http://'):
    _csrf_origins.append(SITE_URL.replace('http://', 'https://'))
CSRF_TRUSTED_ORIGINS = _csrf_origins

# Thêm các domain phụ (subdomain) nếu có
_extra_csrf = env.list('CSRF_TRUSTED_ORIGINS', default=[])
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS += _extra_csrf

# ── Reverse Proxy (Nginx) Settings ────────────────────────────────────
# Khi Django chạy sau Nginx, cần trust X-Forwarded-Proto header
# để nhận biết request là HTTPS (quan trọng cho CSRF khi upload file)
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'corsheaders',
    'rest_framework',
    'channels',
    # Local apps
    'users',
    'crm',
    'sales',
    'orders',
    'inventory',
    'production',
    'notifications',
    'dashboard',
    'approvals',
    'finance',
    'delivery',
    'zalo_integration',
    'facebook_integration',
    'ai_agents',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.FileUploadLimitMiddleware',
    'users.middleware.MaintenanceModeMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'


# ── Database ─────────────────────────────────────────────────────────
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'crm_db',
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': 'db',
        'PORT': '5432',
    }
}


# ── Password validation ───────────────────────────────────────────────
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ── Internationalization ──────────────────────────────────────────────
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = True


# ── Static & Media files ──────────────────────────────────────────────
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'


# ── CORS ─────────────────────────────────────────────────────────────
# Cho phép Frontend ở cổng 5173 được phép lấy dữ liệu
_cors_origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# Tự động thêm SITE_URL vào CORS để hoạt động trên VPS
if SITE_URL and SITE_URL not in _cors_origins:
    _cors_origins.append(SITE_URL)
    # Thêm cả phần frontend (port 3000) nếu site là HTTPS
    if SITE_URL.startswith('https://'):
        _domain = SITE_URL.rstrip('/')
        _cors_origins.append(_domain.replace('https://', 'http://'))

# Thêm các origin tùy chỉnh từ env
_extra_cors = env.list('CORS_ALLOWED_ORIGINS', default=[])
_cors_origins += _extra_cors

CORS_ALLOWED_ORIGINS = list(set(_cors_origins))
CORS_ALLOW_CREDENTIALS = True


# ── Django REST Framework ─────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'users.permissions.IsActiveUserAndCompany',
        'users.permissions.CheckDataMaintenanceMode',
        'users.permissions.IsModuleActivePermission',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# ── Simple JWT ────────────────────────────────────────────────────────
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# ── Django Channels (WebSocket / Real-time) ─────────────────────────────────────
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}


# ── Celery (Background Tasks) ──────────────────────────────────────────
CELERY_BROKER_URL = "redis://redis:6379/1"     # DB 1 — tách khỏi Channels (DB 0)
CELERY_RESULT_BACKEND = "redis://redis:6379/1"
CELERY_TIMEZONE = "Asia/Ho_Chi_Minh"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

try:
    from celery.schedules import crontab
    CELERY_BEAT_SCHEDULE = {
        # Refresh tất cả Zalo token mỗi 12 giờ
        "zalo-refresh-all-tokens": {
            "task": "zalo.refresh_all_tokens",
            "schedule": crontab(minute=0),  # Chạy mỗi giờ 1 lần
        },
        # Dọn rác Social Lead mỗi ngày lúc 3h sáng
        "zalo-cleanup-stale-leads": {
            "task": "zalo.cleanup_stale_leads",
            "schedule": crontab(minute=0, hour=3),
        },
        # Dọn rác Facebook Lead mỗi ngày lúc 3h sáng
        "facebook-cleanup-stale-leads": {
            "task": "facebook.cleanup_stale_leads",
            "schedule": crontab(minute=0, hour=3),
        },
        # Tự động gửi ZNS chúc mừng sinh nhật mỗi ngày lúc 8h sáng
        "zalo-send-birthday-zns": {
            "task": "zalo.send_birthday_zns",
            "schedule": crontab(minute=0, hour=8),
        },
        # Đánh dấu khách ngủ đông mỗi ngày lúc nửa đêm
        "crm-check-inactive-customers": {
            "task": "crm.tasks.check_and_update_inactive_customers",
            "schedule": crontab(minute=0, hour=0),
        },
        # Tự động follow-up khách hàng nếu không phản hồi sau 24h (chạy mỗi 15 phút)
        "ai-agents-drip-followup": {
            "task": "ai_agents.drip_followup",
            "schedule": crontab(minute="*/15"),
        },
    }
except ImportError:
    pass  # Celery chưa được cài — bỏ qua, không crash Django