# Generated by Django 5.2.17 on 2026-08-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0018_add_zalo_token_refresh_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zalomessage',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Tin nhắn Zalo', 'verbose_name_plural': 'Tin nhắn Zalo'},
        ),
    ]
