# Generated by Django 5.2.17 on 2026-08-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0019_alter_zalomessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalomessage',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên người gửi (nếu có)'),
        ),
        migrations.AddField(
            model_name='zalomessage',
            name='sender_role',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('sale', 'Sale'), ('system', 'Hệ thống')], max_length=20, null=True, verbose_name='Vai trò gửi'),
        ),
    ]
