# Generated by Django 5.2.17 on 2026-09-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0021_zalooaconfig_auto_assign_lead_to_customer_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalomessagetemplate',
            name='oa_config',
            field=models.ForeignKey(blank=True, help_text='Tài khoản Zalo OA được dùng để gửi mẫu tin này. Phải khớp với OA đã đăng ký mẫu trên Zalo Cloud.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='zalo_integration.zalooaconfig', verbose_name='Zalo OA gửi'),
        ),
    ]
