# Generated by Django 5.2.17 on 2026-09-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_companysettings_follow_up_remind_before_hours'),
        ('zalo_integration', '0022_add_oa_config_to_zalo_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalomessagelog',
            name='error_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã lỗi Zalo'),
        ),
        migrations.AddField(
            model_name='zalomessagelog',
            name='trigger_object',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nguồn kích hoạt'),
        ),
        migrations.CreateModel(
            name='ZnsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên chiến dịch')),
                ('campaign_type', models.CharField(choices=[('order_confirm', 'Xác nhận Đơn hàng'), ('payment', 'Thu tiền'), ('appointment', 'Nhắc lịch hẹn'), ('marketing', 'Khuyến mãi / Marketing'), ('birthday', 'Chúc mừng Sinh nhật'), ('delivery', 'Giao hàng / Bảo hành'), ('custom', 'Tùy chỉnh khác')], db_index=True, max_length=20, verbose_name='Loại chiến dịch')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Đang hoạt động')),
                ('config_json', models.JSONField(default=dict, verbose_name='Cấu hình chiến dịch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zns_campaigns', to='users.company', verbose_name='Công ty')),
                ('template', models.ForeignKey(blank=True, help_text='OA gửi sẽ tự động lấy từ mẫu đã chọn.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='zalo_integration.zalomessagetemplate', verbose_name='Mẫu ZNS')),
            ],
            options={
                'verbose_name': 'Chiến dịch ZNS',
                'verbose_name_plural': 'Chiến dịch ZNS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='zalomessagelog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='zalo_integration.znscampaign', verbose_name='Chiến dịch ZNS'),
        ),
        migrations.CreateModel(
            name='ZnsSendQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='SĐT nhận')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Tên người nhận')),
                ('template_data', models.JSONField(default=dict, verbose_name='Tham số ZNS')),
                ('trigger_object', models.CharField(blank=True, max_length=100, verbose_name='Nguồn kích hoạt')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='Thời điểm gửi')),
                ('status', models.CharField(choices=[('pending', 'Chờ gửi'), ('sent', 'Đã gửi'), ('failed', 'Thất bại')], db_index=True, default='pending', max_length=10, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, verbose_name='Lỗi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_queue', to='zalo_integration.znscampaign', verbose_name='Chiến dịch')),
            ],
            options={
                'verbose_name': 'Hàng đợi ZNS',
                'verbose_name_plural': 'Hàng đợi ZNS',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='zalo_integr_status_ccb2bd_idx')],
            },
        ),
    ]
