# Generated by Django 5.2.16 on 2026-08-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_item_type_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_target',
            field=models.CharField(blank=True, choices=[('personal', 'Cá nhân'), ('company', 'Công ty')], db_index=True, max_length=20, null=True, verbose_name='Đối tượng thanh toán'),
        ),
    ]
