# Generated by Django 5.2.17 on 2026-08-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_customer_address_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'Dòng đơn hàng', 'verbose_name_plural': 'Dòng đơn hàng'},
        ),
    ]
