# Generated by Django 5.2.17 on 2026-09-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orderitem_options'),
        ('production', '0004_factory_productionorder_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_set', to='production.factory', verbose_name='Nhà máy sản xuất'),
        ),
    ]
