# Generated by Django 5.2.17 on 2026-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ giao hàng'),
        ),
    ]
