# Generated by Django 5.2.17 on 2026-09-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_map_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Định vị giao hàng'),
        ),
    ]
