# Generated by Django 5.2.17 on 2026-09-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_warrantycard_warranty_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_map_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Định vị giao hàng'),
        ),
    ]
