import asyncio
import logging
import os
import sys
from typing import Optional

logger = logging.getLogger(__name__)

MEDIAMTX_LOCAL_RTMP_PORT = 1935
MEDIAMTX_LOCAL_HLS_PORT = 8888
MEDIAMTX_LOCAL_API_PORT = 9997
MEDIAMTX_STREAM_PATH = 'live'

MEDIAMTX_LOCAL_RTMP_URL = f'rtmp://127.0.0.1:{MEDIAMTX_LOCAL_RTMP_PORT}/{MEDIAMTX_STREAM_PATH}'
MEDIAMTX_LOCAL_HLS_URL = f'http://127.0.0.1:{MEDIAMTX_LOCAL_HLS_PORT}/{MEDIAMTX_STREAM_PATH}/index.m3u8'


class MediaMTXManager:
    def __init__(self, external_rtmp_url: Optional[str] = None):
        self.external_rtmp_url = external_rtmp_url
        self.process: Optional[asyncio.subprocess.Process] = None
        self._config_path: Optional[str] = None
        self.is_running = False

    def _locate_binary(self) -> Optional[str]:
        if getattr(sys, 'frozen', False):
            base_dir = os.path.dirname(sys.executable)
        else:
            base_dir = os.path.dirname(os.path.dirname(__file__))

        candidates = [
            os.path.join(base_dir, 'bin', 'mediamtx', 'mediamtx.exe'),
            os.path.join(base_dir, 'bin', 'mediamtx', 'mediamtx'),
        ]
        for c in candidates:
            if os.path.isfile(c):
                return c
        return None

    def _generate_config(self, config_path: str):
        if self.external_rtmp_url:
            rtmp_forward = f"""
      runOnPublish: >-
        ffmpeg -re -i rtmp://127.0.0.1:1935/
        -c copy -f flv {self.external_rtmp_url}
      runOnPublishRestart: yes"""
        else:
            rtmp_forward = ''

        config_content = f"""# MediaMTX runtime config (auto-generated by Autotech Live Studio)
logLevel: warn
logDestinations: [stdout]

rtmp: yes
rtmpAddress: :{MEDIAMTX_LOCAL_RTMP_PORT}

hls: yes
hlsAddress: :{MEDIAMTX_LOCAL_HLS_PORT}
hlsAlwaysRemux: yes
hlsVariant: mpegts
hlsSegmentCount: 7
hlsSegmentDuration: 2s
hlsPartDuration: 500ms

api: yes
apiAddress: :{MEDIAMTX_LOCAL_API_PORT}

paths:
  {MEDIAMTX_STREAM_PATH}:{rtmp_forward}
"""
        with open(config_path, 'w', encoding='utf-8') as f:
            f.write(config_content)
        logger.info(f'[MediaMTX] Config written to {config_path}')

    async def start(self) -> bool:
        binary = self._locate_binary()
        if not binary:
            logger.error('[MediaMTX] mediamtx.exe not found.')
            return False

        binary_dir = os.path.dirname(os.path.abspath(binary))
        self._config_path = os.path.join(binary_dir, 'mediamtx_runtime.yml')
        self._generate_config(self._config_path)

        try:
            flags = 0x08000000 if sys.platform == 'win32' else 0
            self.process = await asyncio.create_subprocess_exec(
                binary, self._config_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                creationflags=flags
            )
            self.is_running = True
            logger.info(f'[MediaMTX] Started (PID {self.process.pid}). RTMP={MEDIAMTX_LOCAL_RTMP_URL} HLS={MEDIAMTX_LOCAL_HLS_URL}')
            asyncio.create_task(self._monitor())
            return True
        except Exception as e:
            logger.error(f'[MediaMTX] Failed to start: {e}')
            return False

    async def _monitor(self):
        if not self.process:
            return
        try:
            while True:
                line = await self.process.stderr.readline()
                if not line:
                    break
                logger.debug(f"[MediaMTX] {line.decode('utf-8', errors='ignore').strip()}")
        except Exception:
            pass
        await self.process.wait()
        self.is_running = False
        logger.warning(f'[MediaMTX] Process exited with code {self.process.returncode}')

    async def stop(self):
        self.is_running = False
        if self.process and self.process.returncode is None:
            self.process.terminate()
            try:
                await asyncio.wait_for(self.process.wait(), timeout=5.0)
            except asyncio.TimeoutError:
                self.process.kill()
                await self.process.wait()
            logger.info('[MediaMTX] Stopped.')

        if self._config_path and os.path.exists(self._config_path):
            try:
                os.remove(self._config_path)
            except OSError:
                pass


