# Generated by Django 5.2.17 on 2026-08-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0026_aiknowledgedocument_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='core_system_rules',
            field=models.TextField(blank=True, help_text='Luật ngầm định cốt lõi của hệ thống', null=True),
        ),
    ]
