# Generated by Django 5.2.17 on 2026-09-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0027_aiagent_core_system_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaikey',
            name='fallback_model',
            field=models.CharField(blank=True, help_text='Model sẽ dùng khi key này được gọi làm nền tảng dự phòng', max_length=100, null=True),
        ),
    ]
