# Generated by Django 5.2.17 on 2026-09-28 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0028_companyaikey_fallback_model'),
        ('inventory', '0021_alter_inventorytransaction_quantity_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_docs', to='inventory.product', verbose_name='Sản phẩm'),
        ),
    ]
