# Generated by Django 5.2.17 on 2026-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0029_aiknowledgedocument_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='tts_speed',
            field=models.FloatField(default=1.0, help_text='Tốc độ đọc (0.25 - 4.0)'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='tts_voice',
            field=models.CharField(default='alloy', help_text='Giọng đọc (vd: alloy, nova, fable, onyx, echo, shimmer)', max_length=50),
        ),
    ]
