# Generated by Django 5.2.16 on 2026-08-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_customer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='priority_level',
            field=models.CharField(choices=[('p1', 'Ưu tiên 1 (Rất cao)'), ('p2', 'Ưu tiên 2 (Cao)'), ('p3', 'Ưu tiên 3 (Trung bình)'), ('p4', 'Ưu tiên 4 (Thấp)')], default='p4', max_length=10, verbose_name='Mức độ ưu tiên'),
        ),
    ]
