# Generated by Django 5.2.16 on 2026-08-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_customer_priority_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expected_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số lượng (bộ) dự kiến'),
        ),
        migrations.AlterField(
            model_name='customerinteraction',
            name='type',
            field=models.CharField(choices=[('call', 'Gọi điện'), ('meeting', 'Gặp mặt'), ('email', 'Gửi Email'), ('zalo', 'Nhắn Zalo'), ('quotation', 'Gửi báo giá'), ('care', 'Chăm sóc'), ('system', 'Hệ thống tự động')], max_length=20, verbose_name='Hình thức'),
        ),
    ]
