# Generated by Django 5.2.16 on 2026-08-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_customer_expected_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expected_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số lượng SP dự kiến'),
        ),
    ]
