# Generated by Django 5.2.16 on 2026-08-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_customer_expected_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên công ty (KH)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã số thuế (KH)'),
        ),
    ]
