# Generated by Django 5.2.17 on 2026-09-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_add_company_name_tax_code_to_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='follow_up_reminded',
            field=models.BooleanField(default=False, verbose_name='Đã nhắc nhở'),
        ),
        migrations.AddField(
            model_name='customer',
            name='follow_up_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hẹn lịch chăm sóc'),
        ),
    ]
