# Generated by Django 5.2.17 on 2026-09-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_customer_follow_up_reminded_customer_follow_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='follow_up_remind_before_minutes',
            field=models.IntegerField(blank=True, help_text='Nếu để trống, sẽ lấy theo mặc định của công ty.', null=True, verbose_name='Tuỳ chỉnh nhắc nhở trước (phút)'),
        ),
    ]
