# Generated by Django 5.2.17 on 2026-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_customer_follow_up_remind_before_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='follow_up_completed',
            field=models.BooleanField(default=False, verbose_name='Đã hoàn thành chăm sóc'),
        ),
    ]
