# Generated by Django 5.2.17 on 2026-09-18 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('error', 'Lỗi'), ('running', 'Đang chạy')], default='running', max_length=20)),
                ('logs', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lịch sử Backup',
                'verbose_name_plural': 'Lịch sử Backup',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemBackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Kích hoạt tự động sao lưu')),
                ('schedule_type', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('hourly', 'Hàng giờ')], default='daily', max_length=20)),
                ('schedule_time', models.TimeField(blank=True, default='02:00:00', null=True, verbose_name='Thời gian chạy (Daily/Weekly)')),
                ('github_repo_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='GitHub Repo URL')),
                ('github_branch', models.CharField(default='backup', max_length=50, verbose_name='GitHub Branch')),
                ('github_access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='GitHub Access Token')),
                ('r2_endpoint_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='R2 Endpoint URL')),
                ('r2_access_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='R2 Access Key')),
                ('r2_secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='R2 Secret Key')),
                ('r2_bucket_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='R2 Bucket Name')),
                ('keep_latest_count', models.IntegerField(default=10, verbose_name='Số lượng bản ghi giữ lại trên Cloud')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Backup',
                'verbose_name_plural': 'Cấu hình Backup',
            },
        ),
    ]
