# Generated by Django 5.2.17 on 2026-09-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembackupconfig',
            name='schedule_day_of_week',
            field=models.IntegerField(blank=True, default=6, null=True, verbose_name='Ngày chạy (Weekly: 0=T2, 6=CN)'),
        ),
    ]
