# Generated by Django 5.2.17 on 2026-09-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_systembackupconfig_schedule_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systembackupconfig',
            name='github_access_token',
        ),
        migrations.RemoveField(
            model_name='systembackupconfig',
            name='github_branch',
        ),
        migrations.RemoveField(
            model_name='systembackupconfig',
            name='github_repo_url',
        ),
    ]
