# Generated by Django 5.2.17 on 2026-09-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_systembackupconfig_github_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistorylog',
            name='action_type',
            field=models.CharField(choices=[('backup', 'Sao lưu (Backup)'), ('restore', 'Phục hồi (Restore)')], default='backup', max_length=20),
        ),
    ]
