# Generated by Django 5.2.17 on 2026-08-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0018_facebookmessage_payload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookmessage',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Tin nhắn Facebook', 'verbose_name_plural': 'Tin nhắn Facebook'},
        ),
    ]
