# Generated by Django 5.2.17 on 2026-08-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0020_facebookmessage_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpageconfig',
            name='auto_assign_lead_to_customer_assignee',
            field=models.BooleanField(default=True, help_text='Nếu bật, khi hội thoại được liên kết với một Khách hàng đã có người phụ trách, hội thoại sẽ tự động được gán cho nhân viên đó.', verbose_name='Tự động gán hội thoại theo Nhân viên phụ trách'),
        ),
    ]
