# Generated by Django 5.2.16 on 2026-07-27 10:15

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventorytransaction_custom_product_name'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.AddField(
            model_name='producttemplate',
            name='image_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, help_text='Vector hình ảnh 512 chiều (CLIP)', null=True),
        ),
    ]
