# Generated by Django 5.2.17 on 2026-08-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_producttemplate_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(choices=[('product', 'Hàng hóa'), ('service', 'Dịch vụ')], default='product', max_length=20, verbose_name='Phân loại'),
        ),
    ]
