# Generated by Django 5.2.17 on 2026-09-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_productcategory_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_inventory_tracked',
            field=models.BooleanField(default=True, help_text='Nếu tắt, các sản phẩm trong danh mục này sẽ không bị trừ kho khi đơn hàng được duyệt.', verbose_name='Kiểm soát kho vận'),
        ),
    ]
