# Generated by Django 5.2.17 on 2026-09-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_productcategory_is_inventory_tracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_sales_target',
            field=models.BooleanField(default=True, help_text='Nếu tắt, các sản phẩm trong danh mục này sẽ không được đếm vào số lượng SP chốt trên báo cáo (thường dùng cho phụ kiện, vật tư phụ).', verbose_name='Tính vào sản lượng chốt'),
        ),
    ]
