# Generated by Django 5.2.17 on 2026-09-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_productcategory_is_sales_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='cái', max_length=50, verbose_name='Đơn vị tính'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='unit',
            field=models.CharField(default='cái', max_length=50, verbose_name='Đơn vị tính'),
        ),
    ]
