# Generated by Django 5.2.17 on 2026-09-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_product_unit_alter_producttemplate_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorytransaction',
            name='inventory_transaction_quantity_gt_0',
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(check=models.Q(quantity__gte=0), name='inventory_transaction_quantity_gte_0'),
        ),
    ]
