# Generated by Django 5.2.16 on 2026-08-15 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_quotationitem_item_type_alter_quotationitem_product'),
        ('users', '0026_companysettings_continuous_sequence_numbering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTemplateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên Block')),
                ('block_type', models.CharField(max_length=50, verbose_name='Loại Block')),
                ('props', models.JSONField(default=dict, verbose_name='Cấu hình Block')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_blocks', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Block mẫu đã lưu',
                'verbose_name_plural': 'Block mẫu đã lưu',
                'ordering': ['-created_at'],
            },
        ),
    ]
