# Generated by Django 5.2.17 on 2026-08-17 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_savedtemplateblock'),
        ('users', '0026_companysettings_continuous_sequence_numbering'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_templates', to='users.company', verbose_name='Công ty sở hữu'),
        ),
        migrations.AddField(
            model_name='quotationtemplate',
            name='is_system_template',
            field=models.BooleanField(default=True, verbose_name='Mẫu hệ thống'),
        ),
    ]
