# Generated by Django 5.2.16 on 2026-08-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_quotationtemplate_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_address_snapshot',
            field=models.TextField(blank=True, verbose_name='Địa chỉ KH (snapshot)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_city_snapshot',
            field=models.CharField(blank=True, max_length=100, verbose_name='Thành phố KH (snapshot)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_company_snapshot',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên công ty KH (snapshot)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_name_snapshot',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên khách hàng (snapshot)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_phone_snapshot',
            field=models.CharField(blank=True, max_length=50, verbose_name='SĐT KH (snapshot)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_tax_code_snapshot',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã số thuế KH (snapshot)'),
        ),
    ]
