# Generated by Django 5.2.17 on 2026-09-28 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0021_alter_inventorytransaction_quantity_constraint'),
        ('users', '0034_companysettings_follow_up_remind_before_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePlatformProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('shopee', 'Shopee'), ('custom', 'Custom/Web')], max_length=50, verbose_name='Nền tảng')),
                ('platform_product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Sản phẩm trên nền tảng')),
                ('affiliate_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Affiliate URL')),
                ('live_price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Giá bán ghi đè (Flash Sale)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_platform_products', to='users.company', verbose_name='Công ty')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_platform_mappings', to='inventory.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Live Platform Product',
                'verbose_name_plural': 'Live Platform Products',
                'constraints': [models.UniqueConstraint(fields=('company', 'product', 'platform'), name='unique_company_product_platform')],
            },
        ),
    ]
