# Generated by Django 5.2.17 on 2026-09-28 03:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0029_aiknowledgedocument_product'),
        ('inventory', '0021_alter_inventorytransaction_quantity_constraint'),
        ('live_sessions', '0001_initial'),
        ('users', '0034_companysettings_follow_up_remind_before_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên thiết bị')),
                ('token_hash', models.CharField(max_length=128, verbose_name='Token Hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần cuối online')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_devices', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Thiết bị Live Studio',
                'verbose_name_plural': 'Thiết bị Live Studio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('shopee', 'Shopee'), ('custom', 'Custom/Web')], max_length=50, verbose_name='Nền tảng')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('ready', 'Sẵn sàng'), ('running', 'Đang chạy'), ('paused', 'Tạm dừng'), ('human_takeover', 'Người kiểm soát'), ('stopped', 'Đã dừng'), ('error', 'Lỗi')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_sessions', to='ai_agents.aiagent', verbose_name='AI Agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='users.company', verbose_name='Công ty')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='live_sessions.livedevice', verbose_name='Thiết bị')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_sessions', to='inventory.product', verbose_name='Sản phẩm đang live')),
            ],
            options={
                'verbose_name': 'Phiên Livestream',
                'verbose_name_plural': 'Phiên Livestream',
                'ordering': ['-created_at'],
            },
        ),
    ]
