# Generated by Django 5.2.17 on 2026-09-28 07:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0002_livedevice_livesession'),
        ('users', '0034_companysettings_follow_up_remind_before_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('shopee', 'Shopee'), ('custom', 'Custom/Web')], max_length=50, verbose_name='Nền tảng')),
                ('account_id', models.CharField(max_length=255, verbose_name='External Account ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Tên hiển thị')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Hết hạn')),
                ('scopes', models.TextField(blank=True, null=True, verbose_name='Scopes')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='Trạng thái')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Tài khoản nền tảng',
                'verbose_name_plural': 'Tài khoản nền tảng',
            },
        ),
        migrations.AddField(
            model_name='livesession',
            name='platform_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='live_sessions.platformaccount', verbose_name='Tài khoản nền tảng'),
        ),
        migrations.AddConstraint(
            model_name='platformaccount',
            constraint=models.UniqueConstraint(fields=('company', 'platform', 'account_id'), name='unique_platform_account'),
        ),
    ]
