# Generated by Django 5.2.17 on 2026-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0003_platformaccount_livesession_platform_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='external_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Phiên Live (Platform)'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='stream_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='RTMP Stream URL'),
        ),
    ]
