# Generated by Django 5.2.17 on 2026-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0004_livesession_external_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='shopee_connection_mode',
            field=models.CharField(blank=True, choices=[('api', 'Shopee API (OAuth)'), ('manual_rtmp', 'Shopee Manual RTMP')], max_length=20, null=True, verbose_name='Chế độ kết nối Shopee'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='stream_key',
            field=models.TextField(blank=True, null=True, verbose_name='Stream Key (encrypted)'),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shopee User ID (Livestream)'),
        ),
    ]
