# Generated by Django 5.2.17 on 2026-10-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0005_phase1e8_shopee_dual_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedevice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Hardware Metrics'),
        ),
    ]
