# Generated by Django 6.0.8 on 2026-10-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0006_livedevice_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedevice',
            name='video_bitrate',
            field=models.CharField(default='2500k', max_length=20, verbose_name='Video Bitrate'),
        ),
        migrations.AddField(
            model_name='livedevice',
            name='video_fps',
            field=models.IntegerField(default=30, verbose_name='FPS'),
        ),
        migrations.AddField(
            model_name='livedevice',
            name='video_resolution',
            field=models.CharField(default='1280x720', max_length=20, verbose_name='Độ phân giải'),
        ),
    ]
