# Generated by Django 5.2.17 on 2026-10-09 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_inventorytransaction_quantity_constraint'),
        ('live_sessions', '0007_livedevice_video_bitrate_livedevice_video_fps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='external_product_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link sản phẩm Affiliate/Shopee/Tiktok'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='inventory.product', verbose_name='Sản phẩm đang live'),
        ),
    ]
