# Generated by Django 5.2.17 on 2026-10-09 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0008_livesession_external_product_link_and_more'),
        ('users', '0037_alter_companysettings_customer_table_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên tài nguyên')),
                ('asset_type', models.CharField(choices=[('avatar', 'Avatar (Video Phông Xanh)'), ('background', 'Phông nền (Background)'), ('overlay', 'Lớp phủ (Overlay/Logo/Frame)'), ('audio', 'Âm thanh (BGM/SFX)')], max_length=20, verbose_name='Loại tài nguyên')),
                ('file', models.FileField(upload_to='live_assets/%Y/%m/', verbose_name='File đính kèm')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='live_assets/thumbnails/%Y/%m/', verbose_name='Ảnh thu nhỏ (Nếu có)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Bỏ trống nếu là tài nguyên hệ thống dùng chung', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_media_assets', to='users.company')),
            ],
            options={
                'verbose_name': 'Live Media Asset',
                'verbose_name_plural': 'Live Media Assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
