# Generated by Django 5.2.17 on 2026-10-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0009_livemediaasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='audio_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_sessions', to='live_sessions.livemediaasset', verbose_name='Âm thanh nền (Tùy chọn)'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='avatar_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_sessions', to='live_sessions.livemediaasset', verbose_name='Avatar (Tùy chọn)'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='background_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_sessions', to='live_sessions.livemediaasset', verbose_name='Phông nền (Tùy chọn)'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='overlay_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overlay_sessions', to='live_sessions.livemediaasset', verbose_name='Lớp phủ/Logo (Tùy chọn)'),
        ),
    ]
