# Generated by Django 5.2.17 on 2026-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0010_livesession_audio_asset_livesession_avatar_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='session_prompt',
            field=models.TextField(blank=True, help_text='Nhập chủ đề, chương trình khuyến mãi... AI sẽ tự động viết thành kịch bản hoàn chỉnh.', null=True, verbose_name='Gợi ý kịch bản (Chủ đề)'),
        ),
    ]
