from enum import Enum

class Capability(Enum):
    AUTH = "AUTH"
    LIVE_STATUS = "LIVE_STATUS"
    LIVE_START = "LIVE_START"
    LIVE_STOP = "LIVE_STOP"
    LIVE_COMMENTS = "LIVE_COMMENTS"
    LIVE_COMMENT_REPLY = "LIVE_COMMENT_REPLY"
    PRODUCT_READ = "PRODUCT_READ"
    PRODUCT_MAPPING = "PRODUCT_MAPPING"
    PRODUCT_ATTACH = "PRODUCT_ATTACH"
    ORDER_EVENTS = "ORDER_EVENTS"
    STREAM_PUBLISH = "STREAM_PUBLISH"
