# Generated by Django 5.2.16 on 2026-08-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_companysettings_is_website_integration_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='continuous_sequence_numbering',
            field=models.BooleanField(default=False, help_text='Nếu bật, số thứ tự (001, 002...) sẽ tăng liên tục không reset về 1 mỗi ngày.', verbose_name='Sinh số thứ tự liên tục'),
        ),
    ]
