# Generated by Django 5.2.17 on 2026-08-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_companysettings_continuous_sequence_numbering'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='custom_info_templates',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách các hạng mục thông tin tùy chỉnh được lưu lại', verbose_name='Mẫu thêm thông tin'),
        ),
    ]
