# Generated by Django 5.2.17 on 2026-08-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_companysettings_custom_info_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auto_assign_target',
            field=models.BooleanField(default=False, help_text='Ghi đè cấu hình Role: Nếu bật, tài khoản này sẽ được chia khách tự động.', verbose_name='Nhận khách tự động'),
        ),
    ]
