# Generated by Django 5.2.17 on 2026-09-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_is_auto_assign_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='code_include_company_prefix',
            field=models.BooleanField(default=True, verbose_name='Bao gồm tiền tố công ty trong mã'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='code_include_date',
            field=models.BooleanField(default=True, verbose_name='Bao gồm ngày tháng trong mã'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='code_include_doc_type',
            field=models.BooleanField(default=True, verbose_name='Bao gồm loại phiếu trong mã'),
        ),
    ]
