# Generated by Django 5.2.17 on 2026-09-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_companysettings_code_include_company_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='independent_sequence_on_derived',
            field=models.BooleanField(default=False, help_text='Đánh số thứ tự mới độc lập khi kế thừa phiếu (Đơn hàng/Xuất kho)'),
        ),
    ]
