# Generated by Django 5.2.17 on 2026-09-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_companysettings_independent_sequence_on_derived'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='list_page_size',
            field=models.PositiveIntegerField(default=1000, help_text='Số lượng bản ghi tối đa được tải về trong các màn hình danh sách (Đơn hàng, Kho vận, v.v...). Mặc định 1000.', verbose_name='Giới hạn số bản ghi danh sách'),
        ),
    ]
