# Generated by Django 5.2.17 on 2026-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_companysettings_list_page_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='require_order_customer',
            field=models.BooleanField(default=False, help_text='Bắt buộc chọn khách hàng khi tạo báo giá và đơn hàng.', verbose_name='Bắt buộc chọn Khách hàng'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='require_order_factory',
            field=models.BooleanField(default=False, help_text='Bắt buộc chọn nhà máy khi tạo đơn hàng/báo giá.', verbose_name='Bắt buộc chọn Nhà máy sản xuất'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='require_order_installation_date',
            field=models.BooleanField(default=False, help_text='Bắt buộc nhập ngày giao hàng/lắp đặt khi tạo báo giá và đơn hàng.', verbose_name='Bắt buộc chọn Ngày giao hàng dự kiến'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='inactive_days_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Nhập 0 để tắt tính năng cảnh báo. Nếu nhập số > 0, hệ thống sẽ tự động gửi thông báo khi khách hàng không có tương tác sau số ngày này.', verbose_name='Ngưỡng cảnh báo khách hàng không hoạt động (ngày)'),
        ),
    ]
