# Generated by Django 5.2.17 on 2026-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_companysettings_require_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='require_order_delivery_address',
            field=models.BooleanField(default=False, help_text='Bắt buộc nhập địa chỉ giao hàng khi tạo đơn hàng/báo giá.', verbose_name='Bắt buộc nhập Địa chỉ giao hàng'),
        ),
    ]
