# Generated by Django 5.2.17 on 2026-09-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_companysettings_require_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='follow_up_remind_before_hours',
            field=models.PositiveIntegerField(default=24, help_text='Số giờ nhắc trước khi đến lịch hẹn chăm sóc khách hàng. Mặc định là 24 giờ.', verbose_name='Thời gian nhắc trước lịch hẹn chăm sóc (giờ)'),
        ),
    ]
