# Generated by Django 5.2.17 on 2026-09-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_companysettings_follow_up_remind_before_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='customer_table_columns',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách các cột được phép hiển thị trên bảng khách hàng (do Admin chọn).', verbose_name='Cột hiển thị bảng khách hàng mặc định'),
        ),
    ]
