# Generated by Django 5.2.17 on 2026-09-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_companysettings_customer_table_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='delivery_table_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='Cột hiển thị bảng giao hàng mặc định'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='inventory_table_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='Cột hiển thị bảng kho vận mặc định'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='order_table_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='Cột hiển thị bảng đơn hàng mặc định'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='production_table_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='Cột hiển thị bảng sản xuất mặc định'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='quotation_table_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='Cột hiển thị bảng báo giá mặc định'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='warranty_table_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='Cột hiển thị bảng bảo hành mặc định'),
        ),
    ]
