# Generated by Django 5.2.17 on 2026-09-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_companysettings_delivery_table_columns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='customer_table_columns',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách các cột được phép hiển thị trên bảng khách hàng (do Admin chọn).', null=True, verbose_name='Cột hiển thị bảng khách hàng mặc định'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='delivery_table_columns',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Cột hiển thị bảng giao hàng mặc định'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='inventory_table_columns',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Cột hiển thị bảng kho vận mặc định'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='order_table_columns',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Cột hiển thị bảng đơn hàng mặc định'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='production_table_columns',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Cột hiển thị bảng sản xuất mặc định'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='quotation_table_columns',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Cột hiển thị bảng báo giá mặc định'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='warranty_table_columns',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Cột hiển thị bảng bảo hành mặc định'),
        ),
    ]
